# Generated by Django 4.1 on 2022-08-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_assignment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdings", name="volume", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="market_day", name="day", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ohlcv", name="stock_id", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ohlcv", name="volume", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orders", name="bid_volume", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orders", name="executed_volume", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="stocks", name="total_volume", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="stocks", name="unallocated", field=models.IntegerField(),
        ),
    ]
