# Generated by Django 4.1 on 2022-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_assignment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=50)),
                ("ifLogged", models.BooleanField(default=False)),
                ("token", models.CharField(default="", max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="users", name="ifLogged",),
        migrations.RemoveField(model_name="users", name="password",),
        migrations.RemoveField(model_name="users", name="token",),
    ]
