# Generated by Django 4.1 on 2022-08-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rest_assignment",
            "0002_user_remove_users_iflogged_remove_users_password_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
        migrations.AddField(
            model_name="users",
            name="ifLogged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="users",
            name="token",
            field=models.CharField(default="", max_length=500, null=True),
        ),
    ]
