# Generated by Django 4.0.4 on 2022-08-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_assignment', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='available_funds',
            field=models.DecimalField(decimal_places=2, default='100.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='blocked_funds',
            field=models.DecimalField(decimal_places=2, default='100.00', max_digits=5),
        ),
    ]
