# Generated by Django 4.1 on 2022-08-08 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_assignment', '0003_alter_users_available_funds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
